import copy
import numpy as np
from collections import defaultdict
import random as random
import matplotlib.pyplot as plt
from pathlib import Path
import random

def ev_monte_carlo(env, pi, gamma, s0, n_samples=200, T=100, V_true = None):
    """
    Estimate the state-value function V^π using every-visit Monte Carlo
    policy evaluation.

    Episodes are generated by following policy π in the environment.
    For each visit of a state within a trajectory, the discounted return
    from that time step onward is computed and used to update the state's
    value estimate via an incremental running average.

    Parameters
    ----------
    env : Environment
        Environment with transition dynamics and reward function.

    pi : dict
        Policy where `pi[s][a]` gives the probability of taking action `a`
        in state `s`.

    gamma : float
        Discount factor applied to future rewards.

    s0 : state or None
        Initial state for each episode. If `None`, episodes start from
        a randomly chosen state.

    n_samples : int, optional
        Number of Monte Carlo episodes to sample.

    T : int, optional
        Maximum trajectory length per episode.

    V_true : dict, optional
        Reference value function used to track convergence error.

    Returns
    -------
    V : dict
        Estimated state-value function.

    dist : np.ndarray or None
        Per-episode error relative to `V_true`, if provided.
    """
    # Value estimate for each state (running average form)
    V = defaultdict(float)

    # Count of how many times each state has been visited
    N = defaultdict(int)
    

    # Optional tracking of L1 error vs true value function
    if V_true is None:
        dist = None
    else:
        dist = np.zeros(n_samples)

    # Loop over Monte Carlo episodes
    for i in range(n_samples):
        
        # MAKE CHANGES HERE
        # Set the initial state
        curr_state = s0
        trajectory = []

        # 1. Generate an episode of maximum length T
        for _ in range(T):
            # Terminate if the battery position (goal) is reached
            if curr_state == env.battery_pos:
                break
                
            # Sample an action from the policy for the current state
            action_probs = pi[curr_state]
            action = np.random.choice(env.actions, p=action_probs)
            
            # Step in the environment
            next_state = env.step(curr_state, action)
            reward = env.reward(next_state, curr_state, action)
            
            # Store the transition
            trajectory.append((curr_state, action, reward))
            
            # Move to the next state
            curr_state = next_state
            
        # 2. Update value estimates using Every-Visit Monte Carlo
        G = 0.0
        # Iterate backwards through the trajectory to calculate the return G
        for s_t, a_t, r_t in reversed(trajectory):
            G = gamma * G + r_t
            
            # Every-visit: update the count and value for EVERY occurrence of s_t
            N[s_t] += 1
            V[s_t] += (G - V[s_t]) / N[s_t]
        
        # Optional diagnostics
        if V_true is not None:
            dist[i] = max(np.abs(V[s] - V_true[s]) for s in env.states())     

    return V, dist

def fv_monte_carlo(env, pi, gamma, s0, n_samples=200, T=100, V_true = None):
    """
    Estimate the state-value function V^π using first-visit Monte Carlo
    policy evaluation.

    Episodes are generated by following policy π in the environment.
    For each state, only the first occurrence within an episode is used
    to compute a discounted return and update the state's value estimate
    via an incremental running average.

    Parameters
    ----------
    env : Environment
        Environment with transition dynamics and reward function.

    pi : dict
        Policy where `pi[s][a]` gives the probability of taking action `a`
        in state `s`.

    gamma : float
        Discount factor applied to future rewards.

    s0 : state or None
        Initial state for each episode. If `None`, episodes start from
        a randomly chosen state.

    n_samples : int, optional
        Number of Monte Carlo episodes to sample.

    T : int, optional
        Maximum trajectory length per episode.

    V_true : dict, optional
        Reference value function used to track convergence error.

    Returns
    -------
    V : dict
        Estimated state-value function.

    dist : np.ndarray or None
        Per-episode error relative to `V_true`, if provided.
    """
    # Value estimate for each state (running average form)
    V = defaultdict(float)

    # Count of how many times each state has been visited
    N = defaultdict(int)

    # Optional tracking of L1 error vs true value function
    if V_true is None:
        dist = None
    else:
        dist = np.zeros(n_samples)

    # Loop over Monte Carlo episodes
    for i in range(n_samples):
        
        # MAKE CHANGES HERE

        curr_state = s0

        trajectory = []

        for _ in range(T):
            # Terminate if the battery position (goal) is reached
            if curr_state == env.battery_pos:
                break
                
            # Sample an action from the policy for the current state
            action_probs = pi[curr_state]
            action = np.random.choice(env.actions, p=action_probs)
            
            # Step in the environment
            next_state = env.step(curr_state, action)
            reward = env.reward(next_state, curr_state, action)
            
            # Store the transition
            trajectory.append((curr_state, action, reward))
            
            # Move to the next state
            curr_state = next_state

        G = 0.0
        # Pre-extract states to easily check for prior visits
        states_in_trajectory = [step[0] for step in trajectory]
        
        # Iterate backwards through the trajectory to calculate the return G
        for t in range(len(trajectory) - 1, -1, -1):
            s_t, a_t, r_t = trajectory[t]
            G = gamma * G + r_t
            
            # First-visit check: only update if s_t does not appear earlier in the episode
            if s_t not in states_in_trajectory[:t]:
                N[s_t] += 1
                V[s_t] += (G - V[s_t]) / N[s_t]
        
        # Optional diagnostics
        if V_true is not None:
            dist[i] = max(np.abs(V[s] - V_true[s]) for s in env.states())

    return V, dist