device: cpu

env:
  name: Pendulum-v1

logging:
  project: sac-pendulum

collector:
  total_frames: 50_000
  frames_per_batch: 1_000
  init_random_frames: 1_000

buffer:
  buffer_size: 50_000
  batch_size: 256

optim:
  actor_lr: 3e-4
  critic_lr: 3e-4
  tau: 0.005

loss:
  gamma: 0.99
  num_updates: 1

alpha:
  autotune: true
  value: 0.2
  lr: 3e-4

evaluation:
  eval_step_freq: 5000
  episodes: 10